version: "3.8"

services:
  nginx-amplify:
    image: nginx-amplify
    container_name: nginx-amplify
    build:
     context: nginx-amplify/
     dockerfile: Dockerfile
    environment:
      - DOMAIN=${DOMAIN}
      - API_KEY=${API_KEY}
      - AMPLIFY_IMAGENAME=${AMPLIFY_IMAGENAME}
    volumes:
      - ./nginx-amplify/conf.d:/etc/nginx/templates
      - ./nginx-amplify/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/nginx/ssl
      - ./nginx-amplify/certbot/data:/var/www/certbot
    ports:
      - 8080:8080
      - 4443:4443
    restart: unless-stopped
    networks:
      - node_pilot

  certbot-renew:
    image: certbot-renew
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    build:
     context: certbot/
     dockerfile: Dockerfile
    container_name: certbot-renew

networks:
  node_pilot:
    external: true
    name: node-manager-network
