version: "3.8"

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./nginx/conf.d:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/nginx/ssl
      - ./nginx/certbot/data:/var/www/certbot
      - ./nginx/logs:/var/log/nginx
    ports:
      - 8080:8080
      - 4443:4443
    restart: unless-stopped
    networks:
      - node_pilot

  certbot-renew:
    image: certbot-renew
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    build:
     context: certbot/
     dockerfile: Dockerfile
    container_name: certbot-renew

networks:
  node_pilot:
    external: true
    name: node-manager-network
